# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-25 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateme', '0002_auto_20191125_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='/images/default.png', upload_to='images/'),
        ),
    ]
